version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cryptoApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uheapo4gy2d0"
s3_prefix = "cryptoApp"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
profile = "SAM_user"
