AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  crypto

  Sample SAM Template for crypto

Globals:
  Function:
    Timeout: 300

Resources:
  AppBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Effect: Allow
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref AppBucket
                - /*
            Principal: "*"

  GetCrypto:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_crypto/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - S3WritePolicy:
            BucketName: !Ref AppBucket
      Environment:
        Variables:
          S3_BUCKET: !Ref AppBucket
          S3_STORAGE_PATH: documents/
          S3_OBJECT_PREFIX: cryto_prices_
          S3_OBJECT_SUFFIX: .json
      Events:
        OncePerDay:
          Type: Schedule # More info about the Schedule Event Source: https://github.com/aws/serverless-application-model/blob/master/docs/internals/generated_resources.rst#schedule
          Properties:
            Schedule: cron(0 0 * * ? *) # every day at 0:00 UTC

  GetSheet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_sheet/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 100
      Policies: AWSLambdaExecute
      Events:
        GetSheetEvent:
          Type: S3
          Properties:
            Bucket: !Ref AppBucket
            Events: s3:ObjectCreated:*
#Outputs:
#  GetCrypto:
#    Description: "API Gateway endpoint URL for Prod stage for Hello EFS function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
